### ISSUE TITLE
Metric label instance conflict with prometheus

### ISSUE THREAD

**Issue by kelein** [lucianjon/zk-exporter#1]
The metric with label `instance` will conflict with prometheus when it be pulled into.
The original metric the exporter exposed is like:
```
zk_znode_count{instance="localhost:2181"}
```
But when it be pulled into promethes it will re-labeled by prometheus like:
```
zk_znode_count{exported_instance="localhost:2181",instance="localhost:9120",job="zk_export"}
```
I think the `instance` label is only owned for exporter itself,
So I suggest that we should rename zk metric label instead of `instance`.

**Comment by lucianjon** [comment]
Hi, sorry for the late response. I've been on holiday for a couple weeks. Do you have something in your prometheus config to rename the `instance` label to something else? We've been using that label across a few different services and haven't run into prometheus renaming it yet

**Comment by kelein** [comment]
The Prometheus server will attach an `instance` label to each scraped metric that does not already have one. The automatically attached instance label contains the host and port of the target scraped. If a metric already has an instance label, an `exporter_instance` label is attached instead.

**Comment by kelein** [comment]
This is the official advise here: prometheus/prometheus#490

**Comment by lucianjon** [comment]
Ah right, we've always gone with the default `honor_labels` config which is why we've never seen this. I've updated the label here to be `zk_instance`. Let me know if you have any other issues
