### ISSUE TITLE
about zookeeper 3.3.6

### ISSUE THREAD

**Issue by andydodo** [lucianjon/zk-exporter#5]
Dear sir，I would like to use the zookeeper_exporter. However my zookeeper is work at 3.3.6 ( zookeeper doesn't upgrade）. How can it compatible with 3.3.6 . Please help me solve this issue

**Comment by lucianjon** [comment]
Hi, you won't gain much from this service on anything < 3.4.0. All of the commands bar the ping were introduced in 3.4.x.
